const cron = require('node-cron');

const L = {
  meeting: { zh: '定时例会', en: 'Scheduled Meeting' },
  meetingPrompt: { zh: '请简要回复（200字以内）。', en: 'Please reply briefly (200 words max).' },
  meetingTime: { zh: '时间', en: 'Time' },
  meetingParticipants: { zh: '参与者', en: 'Participants' },
  meetingNotice: { zh: '各 Agent 已收到通知并开始汇报，请在虾聊中查看详细回复。', en: 'All Agents have been notified. Check their replies in Chats.' },
  supervisionData: { zh: '{name} 的工作数据', en: 'Work data of {name}' },
  supervisionMessages: { zh: '消息数', en: 'Messages' },
  supervisionTasks: { zh: '任务完成数', en: 'Tasks completed' },
  supervisionPosts: { zh: '动态发帖数', en: 'Community posts' },
  supervisionComments: { zh: '评论数', en: 'Comments' },
  weeklyTitle: { zh: '{name} 成长周报', en: '{name} Weekly Report' },
  weeklyPeriod: { zh: '统计周期', en: 'Reporting Period' },
  weeklyMetrics: { zh: '工作指标', en: 'Work Metrics' },
  weeklyMetric: { zh: '指标', en: 'Metric' },
  weeklyValue: { zh: '数值', en: 'Value' },
  weeklyMsgProc: { zh: '消息处理', en: 'Messages processed' },
  weeklyTaskDone: { zh: '任务完成', en: 'Tasks completed' },
  weeklyPosts: { zh: '动态发帖', en: 'Community posts' },
  weeklyComments: { zh: '评论互动', en: 'Comment interactions' },
  weeklyRating: { zh: '综合评分', en: 'Overall rating' },
  weeklyActivity: { zh: '活跃度', en: 'Activity' },
  weeklyLastActive: { zh: '最后活跃', en: 'Last active' },
  weeklyNoRecord: { zh: '无记录', en: 'No record' },
  weeklyNone: { zh: '暂无', en: 'N/A' },
  weeklyAuto: { zh: '此报告由系统自动生成', en: 'This report was automatically generated by the system' },
  weeklyTag: { zh: '周报', en: 'Weekly' },
  autoTag: { zh: '自动', en: 'Auto' },
  reviewTag: { zh: '审阅', en: 'Review' },
  groupReviewTask: { zh: '群组工作汇报', en: 'Group Work Review' },
  groupReviewYouAre: { zh: '你是 {leader}，作为「{group}」的组长，请汇总团队成员的近期工作表现。', en: 'You are {leader}, the leader of "{group}". Please summarize the recent work of your team members.' },
  groupReviewData: { zh: '各成员工作数据', en: 'Team members work data' },
  groupReviewAsk: { zh: '请给出简短的团队工作总结（200字以内），包括整体评价和改进建议。', en: 'Please provide a brief team summary (200 words max), including overall assessment and suggestions.' },
  socialBrowsing: { zh: '动态互动', en: 'Community Interaction' },
  socialYouAre: { zh: '你是 {name}，正在浏览动态。', en: 'You are {name}, browsing the community.' },
  socialTopics: { zh: '你关注的话题', en: 'Topics you follow' },
  socialStyle: { zh: '你的社交风格', en: 'Your social style' },
  socialSawPost: { zh: '你看到了这条帖子', en: 'You saw this post' },
  socialTitle: { zh: '标题', en: 'Title' },
  socialContent: { zh: '内容', en: 'Content' },
  socialNoTitle: { zh: '(无标题)', en: '(no title)' },
  socialAsk: { zh: '如果你觉得值得评论，请用一两句话评论（50字以内）。如果不想评论，回复"跳过"。', en: 'If you think it\'s worth commenting, reply in 1-2 sentences (50 words max). If not, reply "skip".' },
};

function tl(key, params) {
  const entry = L[key];
  if (!entry) return key;
  let txt = entry.zh + ' / ' + entry.en;
  if (params) Object.keys(params).forEach(k => { txt = txt.replace(new RegExp('\\{' + k + '\\}', 'g'), params[k]); });
  return txt;
}

function tSingle(key, lang, params) {
  const entry = L[key];
  if (!entry) return key;
  let txt = entry[lang] || entry.zh;
  if (params) Object.keys(params).forEach(k => { txt = txt.replace(new RegExp('\\{' + k + '\\}', 'g'), params[k]); });
  return txt;
}

class Scheduler {
  constructor(ctx) {
    this.ctx = ctx;
    this.jobs = new Map();
    this.socialTimer = null;
    this.weeklyReportJob = null;
    this.supervisionJob = null;
  }

  start() {
    this.reload();
    this.startSocialLoop();
    this.startSupervisionLoop();
    this.startWeeklyReport();
  }

  stop() {
    for (const job of this.jobs.values()) job.stop();
    this.jobs.clear();
    if (this.socialTimer) clearInterval(this.socialTimer);
    if (this.weeklyReportJob) this.weeklyReportJob.stop();
    if (this.supervisionJob) this.supervisionJob.stop();
  }

  reload() {
    for (const job of this.jobs.values()) job.stop();
    this.jobs.clear();
    const schedules = this.ctx.getSchedules();
    for (const sched of schedules) {
      if (!sched.enabled || !cron.validate(sched.cron)) continue;
      const job = cron.schedule(sched.cron, () => this.runMeeting(sched.id));
      this.jobs.set(sched.id, job);
      console.log(`[scheduler] registered: ${sched.name} (${sched.cron})`);
    }
  }

  // ── Scheduled Meetings ──

  async runMeeting(scheduleId) {
    const schedules = this.ctx.getSchedules();
    const sched = schedules.find(s => s.id === scheduleId);
    if (!sched) return;
    if (!this.ctx.isGwConnected()) { console.log('[scheduler] skip meeting, gw not connected'); return; }

    console.log(`[scheduler] running meeting: ${sched.name}`);
    const agents = this.ctx.getAgents();
    const participants = sched.participants.length > 0
      ? sched.participants.map(pid => agents.find(a => a.id === pid)).filter(Boolean)
      : agents;

    const responses = [];
    for (const agent of participants) {
      try {
        const prompt = `[${tSingle('meeting','zh')} - ${sched.name}]\n\n${sched.template}\n\n${tSingle('meetingPrompt','zh')}`;
        const result = await this.ctx.sendToGateway(agent.id, agent.id, prompt);
        if (result.ok) {
          await this.sleep(5000);
          responses.push({ agent: agent.name, agentId: agent.id, status: 'ok' });
        }
      } catch (e) {
        responses.push({ agent: agent.name, agentId: agent.id, status: 'error', error: e.message });
      }
    }

    sched.lastRun = Date.now();
    this.ctx.saveSchedules();

    const summary = [
      `## ${sched.name}`,
      `${tSingle('meetingTime','zh')}: ${new Date().toLocaleString('zh-CN')}`,
      `${tSingle('meetingParticipants','zh')}: ${responses.map(r => r.agent).join(', ')}`,
      '',
      tSingle('meetingNotice','zh'),
    ].join('\n');

    this.ctx.emitCommunityEvent('meeting_summary', {
      title: `${sched.name} - ${new Date().toLocaleDateString('zh-CN')}`,
      content: summary,
      participants: responses.map(r => r.agentId),
    });
  }

  // ── Group Leader Review ──

  startSupervisionLoop() {
    this._groupJobs = this._groupJobs || {};
    const groups = this.ctx.getGroups ? this.ctx.getGroups() : [];
    const defaultCron = this.ctx.getSettings?.()?.supervisionCron || '0 18 * * 1-5';
    let count = 0;
    for (const g of groups) {
      if (!g.leader) continue;
      const cronExpr = g.reviewCron || defaultCron;
      if (!cron.validate(cronExpr)) continue;
      this._groupJobs[g.id] = cron.schedule(cronExpr, () => this.runGroupReview(g.id));
      count++;
    }
    if (count) console.log(`[scheduler] group review: ${count} group(s) with leaders`);
    else console.log('[scheduler] group review: no groups with leaders');
  }

  reloadSupervision() {
    if (this._groupJobs) { for (const j of Object.values(this._groupJobs)) j.stop(); }
    this._groupJobs = {};
    this.startSupervisionLoop();
  }

  async runGroupReview(groupId) {
    if (!this.ctx.isGwConnected()) return;
    const groups = this.ctx.getGroups ? this.ctx.getGroups() : [];
    const g = groups.find(x => x.id === groupId);
    if (!g || !g.leader) return;

    const agents = this.ctx.getAgents();
    const leaderAgent = agents.find(a => a.id === g.leader);
    if (!leaderAgent) return;

    const allMetrics = this.ctx.getMetrics ? this.ctx.getMetrics() : {};
    const memberAgents = (g.members || []).filter(id => id !== g.leader).map(id => agents.find(a => a.id === id)).filter(Boolean);
    if (!memberAgents.length) return;

    const lines = memberAgents.map(a => {
      const m = allMetrics[a.id] || {};
      return `- ${a.name}: ${tSingle('supervisionMessages','zh')} ${m.messages||0}, ${tSingle('supervisionTasks','zh')} ${m.tasks||0}, ${tSingle('supervisionPosts','zh')} ${m.posts||0}`;
    });

    const reviewPrompt = [
      `[${tSingle('groupReviewTask','zh')}]`,
      tSingle('groupReviewYouAre','zh', { leader: leaderAgent.name, group: g.name }),
      '',
      `${tSingle('groupReviewData','zh')}:`,
      ...lines,
      '',
      tSingle('groupReviewAsk','zh'),
    ].join('\n');

    try {
      this.ctx.sendToGateway(g.id, leaderAgent.id, reviewPrompt);
      console.log(`[scheduler] group review triggered: ${g.name} (leader: ${leaderAgent.name})`);
    } catch (e) {
      console.error(`[scheduler] group review failed for ${g.name}:`, e.message);
    }
  }

  // ── Weekly Growth Report ──

  startWeeklyReport() {
    this.weeklyReportJob = cron.schedule('0 10 * * 1', () => this.generateWeeklyReports());
    console.log('[scheduler] weekly report: Monday 10:00');
  }

  async generateWeeklyReports() {
    const agents = this.ctx.getAgents();
    const allMetrics = this.ctx.getMetrics ? this.ctx.getMetrics() : {};
    const now = new Date();
    const weekStart = new Date(now); weekStart.setDate(now.getDate() - 7);

    for (const agent of agents) {
      const m = allMetrics[agent.id];
      if (!m) continue;

      const avgRating = m.ratings?.length
        ? (m.ratings.reduce((s, r) => s + r.score, 0) / m.ratings.length).toFixed(1)
        : tSingle('weeklyNone','zh');

      const content = [
        `## ${tSingle('weeklyTitle','zh',{name:agent.name})}`,
        `${tSingle('weeklyPeriod','zh')}: ${weekStart.toLocaleDateString('zh-CN')} ~ ${now.toLocaleDateString('zh-CN')}`,
        '',
        `### ${tSingle('weeklyMetrics','zh')}`,
        `| ${tSingle('weeklyMetric','zh')} | ${tSingle('weeklyValue','zh')} |`,
        `|------|------|`,
        `| ${tSingle('weeklyMsgProc','zh')} | ${m.messages || 0} |`,
        `| ${tSingle('weeklyTaskDone','zh')} | ${m.tasks || 0} |`,
        `| ${tSingle('weeklyPosts','zh')} | ${m.posts || 0} |`,
        `| ${tSingle('weeklyComments','zh')} | ${m.comments || 0} |`,
        `| ${tSingle('weeklyRating','zh')} | ${avgRating} |`,
        '',
        `### ${tSingle('weeklyActivity','zh')}`,
        `${tSingle('weeklyLastActive','zh')}: ${m.lastActive ? new Date(m.lastActive).toLocaleString('zh-CN') : tSingle('weeklyNoRecord','zh')}`,
        '',
        `---`,
        `*${tSingle('weeklyAuto','zh')}*`,
      ].join('\n');

      this.ctx.createPost({
        authorType: 'system', authorId: 'system',
        title: `${tSingle('weeklyTitle','zh',{name:agent.name})} - ${now.toLocaleDateString('zh-CN')}`,
        content,
        topic: 'daily', type: 'log', tags: [tSingle('weeklyTag','zh'), tSingle('autoTag','zh')],
      });
    }

    this.ctx.broadcast({ type: 'community_update' });
    console.log(`[scheduler] weekly reports generated for ${agents.length} agents`);
  }

  // ── Autonomous Social Behavior ──

  startSocialLoop() {
    const intervalMs = 3600000;
    this.socialTimer = setInterval(() => this.socialCycle(), intervalMs);
    setTimeout(() => this.socialCycle(), 120000);
    console.log('[scheduler] social loop: every 1h');
  }

  async socialCycle() {
    if (!this.ctx.isGwConnected()) return;
    const agents = this.ctx.getAgents();
    if (!agents.length) return;

    const profiles = this.ctx.getProfiles ? this.ctx.getProfiles() : {};

    const eligibleAgents = agents.filter(a => {
      const prof = profiles[a.id] || {};
      const activity = prof.socialActivity || 'medium';
      if (activity === 'low') return Math.random() < 0.2;
      if (activity === 'high') return Math.random() < 0.8;
      return Math.random() < 0.4;
    });

    if (!eligibleAgents.length) return;

    const agent = eligibleAgents[Math.floor(Math.random() * eligibleAgents.length)];
    const prof = profiles[agent.id] || {};
    const interests = prof.socialInterests || [];

    try {
      const postsResp = await this.fetchRecentPosts();
      if (!postsResp.length) return;

      const targetPost = this.findRelevantPost(postsResp, interests, agent.id);
      if (!targetPost) return;

      const prompt = [
        `[${tSingle('socialBrowsing','zh')}]`,
        tSingle('socialYouAre','zh',{name:agent.name}),
        interests.length ? `${tSingle('socialTopics','zh')}: ${interests.join(', ')}` : '',
        prof.socialStyle ? `${tSingle('socialStyle','zh')}: ${prof.socialStyle}` : '',
        ``,
        `${tSingle('socialSawPost','zh')}:`,
        `${tSingle('socialTitle','zh')}: ${targetPost.title || tSingle('socialNoTitle','zh')}`,
        `${tSingle('socialContent','zh')}: ${targetPost.content.slice(0, 300)}`,
        ``,
        tSingle('socialAsk','zh'),
      ].filter(Boolean).join('\n');

      const result = await this.ctx.sendToGateway(agent.id, agent.id, prompt);
      if (result.ok) {
        await this.sleep(10000);
        console.log(`[social] ${agent.name} browsed community post ${targetPost.id}`);
      }
    } catch (e) {
      console.error(`[social] cycle failed:`, e.message);
    }
  }

  fetchRecentPosts() {
    const fs = require('fs');
    const path = require('path');
    try {
      const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'community-posts.json'), 'utf8'));
      return data.slice(-20).reverse();
    } catch { return []; }
  }

  findRelevantPost(posts, interests, agentId) {
    const uncommented = posts.filter(p => {
      if (p.authorId === agentId) return false;
      const hasCommented = (p.comments || []).some(c => c.authorId === agentId);
      return !hasCommented;
    });
    if (!uncommented.length) return null;

    if (interests.length) {
      const relevant = uncommented.filter(p =>
        interests.some(i => (p.title + p.content + (p.tags || []).join(' ')).includes(i))
      );
      if (relevant.length) return relevant[Math.floor(Math.random() * relevant.length)];
    }

    return uncommented[Math.floor(Math.random() * uncommented.length)];
  }

  sleep(ms) { return new Promise(r => setTimeout(r, ms)); }
}

module.exports = Scheduler;
